package com.finflow.application.entity;

public enum LoanStatus {
    DRAFT,
    PERSONAL_DETAILS_ADDED,
    EMPLOYMENT_DETAILS_ADDED,
    LOAN_DETAILS_ADDED,
    DOCUMENTS_COMPLETED,
    SUBMITTED,
    DOCS_VERIFIED,
    DOCS_PENDING,
    UPLOADED,
    PARTIAL,
    REVIEW,
    VERIFIED,
    REUPLOAD,
    DOCS_REUPLOADED,
    FAIL,
    APPROVED,
    REJECTED
}
